# Header

menu:
  主页: /
  瞎推荐: /categories/recommend
  小工具: /categories/utils
  随便聊聊: /categories/shownTalk
  一些基础的东西: /categories/basis
  # 随笔: /tags/随笔

# SubNav
subnav:
  rss: "http://dcfun.github.io/atom.xml"
  github: "https://github.com/dcfun"
  weibo: "http://weibo.com/uu78999"
  #zhihu: "#"
  #douban: "#"
  #mail: "uu78999@gmail.com"
  #facebook: "https://www.facebook.com/dcfun.fun"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# Miscellaneous
google_analytics: ''
favicon: /img/favicon.ico

#头像url
avatar: "/img/tblogs.png"
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: true
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  杜帅: http://blog.csdn.net/lotluck
  王伟豪: http://blog.csdn.net/wwh578867817
  cutter_point: http://blog.csdn.net/cutter_point
  叉叉哥: http://xxgblog.com

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 我是谁，我从哪里来，我到哪里去？我就是我，是颜色不一样的吃货…